package com.mycompany.gestaousuarios.view;

import javax.swing.JButton;
import javax.swing.JComboBox;

public class LogConfigView extends javax.swing.JInternalFrame {

    /**
     * Creates new form LogConfigView
     */
    public LogConfigView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboLog = new javax.swing.JComboBox<>();
        buttonLogSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fecharButton = new javax.swing.JButton();

        setTitle("Tipo de log");

        comboLog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSV", "JSON" }));
        comboLog.setToolTipText("");

        buttonLogSalvar.setText("Salvar");

        jLabel1.setText("Tipo de Log : ");

        fecharButton.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fecharButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(buttonLogSalvar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogSalvar)
                    .addComponent(fecharButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getButtonLogSalvar() {
        return buttonLogSalvar;
    }

    public JComboBox<String> getComboLog() {
        return comboLog;
    }

    public JButton getFecharButton() {
        return fecharButton;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogSalvar;
    private javax.swing.JComboBox<String> comboLog;
    private javax.swing.JButton fecharButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
